config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'

  resources :kittens

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates_presence_of :name, :age, :cuteness, :softness
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: 'Successfully created kitten'
    else
      render :new, status: :unprocessable_entity, alert: 'Improper kitten parameters!'
    end
  end

  def edit
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity, alert: 'Improper kitten parameters!'
    end
  end

  def destroy
    @kitten.destroy
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<b>Name:</b> <%= kitten.name %>
<br>
<b>Age:</b> <%= kitten.age %>
<br>
<b>Cuteness:</b> <%= kitten.cuteness %>
<br>
<b>Softness:</b> <%= kitten.softness %>
<br>

app/views/kittens/_kitten_form.html.erb
<%= form.label :name %>
<%= form.text_field :name%>
<br>
<%= form.label :age %>
<%= form.text_field :age %>
<br>
<%= form.label :cuteness %>
<%= form.text_field :cuteness %>
<br>
<%= form.label :softness %>
<%= form.text_field :softness %>
<br>

app/views/kittens/edit.html.erb
<%= form_with model: @kitten do |form| %>
  <%= render partial: 'kitten_form', locals: { form: form } %>
  <%= form.submit 'Update Kitten' %>
<% end %>
<%= link_to 'Delete', kitten_path(@kitten), data: { turbo_method: :delete, turbo_confrirm: 'Are you sure?' } %>

app/views/kittens/index.html.erb
<% @kittens.each do |kitten| %>
  <%= render partial: 'kitten', locals: {kitten: kitten }%>
<% end %>

app/views/kittens/new.html.erb
<%= form_with model: @kitten do |form| %>
  <%= render partial: 'kitten_form', locals: { form: form } %>
  <%= form.submit 'Create Kitten' %>
<% end %>

app/views/kittens/show.html.erb
<%= render partial: 'kitten', locals: { kitten: @kitten } %>
<%= link_to 'Delete', kitten_path(@kitten), data: { turbo_method: :delete, turbo_confrirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>